# Generated by Django 4.2.6 on 2023-10-13 05:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='audio_file_url',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='text_file_url',
            field=models.FileField(upload_to=main.models.transcript_file_upload),
        ),
    ]
