# Generated by Django 4.2.6 on 2023-10-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_transcript_audio_file_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeated_lines', models.CharField(max_length=1000)),
                ('psychologists_notes', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=1000)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
