# Generated by Django 4.2.6 on 2023-10-17 15:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_transcript_audio_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='generated_transcript',
            field=models.FileField(null=True, upload_to=main.models.transcript_file_upload),
        ),
    ]
