# Generated by Django 4.2.6 on 2023-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_patient_emergency_contact_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnote',
            name='client_history',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='diagnosis',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='psychologists_notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='repeated_lines',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
